### ISSUE TITLE
GatheringFuture exception was never retrieved

### ISSUE THREAD

**Issue by tumb1er** [just-work/fffw#163]
```
2023-08-08 09:29:01,629 asyncio ERROR: _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/data/lst/virtualenv/lib/python3.11/site-packages/fffw/wrapper/base.py", line 146, in read
    async for line in UniversalLineReader(reader):
  File "/data/lst/virtualenv/lib/python3.11/site-packages/fffw/wrapper/base.py", line 57, in readlines
    block = await self.reader.read(self.blocksize)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 690, in read
    await self._wait_for_data('read')
  File "/usr/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

```

When stopping ffmpeg via cancellation, this happens ^.

Looks like additional CancelledError handling is needed, see https://stackoverflow.com/questions/63353358/weird-behaviour-of-asyncio-cancellederror-and-gatheringfuture-exception-was-ne

**Comment by tumb1er** [comment]
Some fixes while debugging locally:

```
Index: fffw/wrapper/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/fffw/wrapper/base.py b/fffw/wrapper/base.py
--- a/fffw/wrapper/base.py	
+++ b/fffw/wrapper/base.py	(date 1691490346661)
@@ -122,7 +122,7 @@
                         exc_type: Optional[Type[BaseException]],
                         exc_val: Optional[BaseException],
                         exc_tb: TracebackType) -> None:
-        await self.proc.wait()
+        await asyncio.shield(self.proc.wait())
 
     def __call__(self) -> Tuple[int, str, str]:
         return asyncio.get_event_loop().run_until_complete(self.run())
@@ -174,23 +174,30 @@
     async def run(self) -> Tuple[int, str, str]:
         async with self as p:
             try:
-                await asyncio.wait_for(
-                    asyncio.shield(asyncio.gather(
-                        # write input data to stdin
-                        self.write(p.stdin, self.stdin),
-                        # read output from stdout
-                        self.read(p.stdout, self.stdout, self.output),
-                        # read output from stderr
-                        self.read(p.stderr, self.stderr, self.errors),
-                        # wait for process termination
-                        p.wait(),
-                    )),
+                f = asyncio.gather(
+                    # write input data to stdin
+                    self.write(p.stdin, self.stdin),
+                    # read output from stdout
+                    self.read(p.stdout, self.stdout, self.output),
+                    # read output from stderr
+                    self.read(p.stderr, self.stderr, self.errors),
+                    # wait for process termination
+                    p.wait(),
+                )
+                await asyncio.wait_for(
+                    f,
                     timeout=self.timeout)
             except asyncio.TimeoutError:
                 try:
                     self.proc.kill()
                 except ProcessLookupError:
                     pass
+            finally:
+                try:
+                    await f
+                except asyncio.CancelledError:
+                    pass
+
         return (cast(int, self.proc.returncode),
                 self.output.getvalue(),
                 self.errors.getvalue())
```

**Comment by tumb1er** [comment]
This should be addressed after fffw got official support for asyncronous run
