### ISSUE TITLE
Invalid version: 'dev'

### ISSUE THREAD

**Issue by tumb1er** [just-work/fffw#164]
https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647

Looks like temporary versioning is not considered as correct anymore:
<details><summary>Details</summary>
<p>

```
error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      fatal: No names found, cannot describe anything.
      /tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 20[23](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:24)-Sep-[26](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:27), you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/dist.py:510: SetuptoolsDeprecationWarning: Invalid version: 'dev'.
      !!
      
              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
        self._validate_version(self.metadata.version)
      running egg_info
      /tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py:1[31](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:32): SetuptoolsDeprecationWarning: Invalid version: 'dev'.
      !!
      
              ********************************************************************************
              Version 'dev' is not valid according to PEP 440.
      
              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 1[32](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:33), in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line [33](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:34)8, in run_setup
          exec(code, locals())
        File "<string>", line 64, in <module>
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 12[34](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:35), in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 9[87](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:88), in run_command
          cmd_obj.ensure_finalized()
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 218, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fmi10yhf/overlay/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 1[98](https://github.com/just-work/fffw/actions/runs/5808486098/job/15745355647#step:4:99), in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'dev'
```

</p>
</details>

**Comment by tumb1er** [comment]
Closed with #165
